use cs332h25;

DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Department;
DROP TABLE IF EXISTS Professors; 
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Section; 
DROP TABLE IF EXISTS ProfessorDegrees; 
DROP TABLE IF EXISTS Minor;
DROP TABLE IF EXISTS Enrollment; 